info:
  contact: {}
paths:
  /get_user_list:
    get:
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      tags:
      - 扶뒬못
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 扶뒬못
swagger: "2.0"
